//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ANSTECHNOLOGIES.Resources.Views.Home.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AddressDesc {
            get {
                return ResourceManager.GetString("AddressDesc", resourceCulture);
            }
        }
        
        public static string AIBasedSystems {
            get {
                return ResourceManager.GetString("AIBasedSystems", resourceCulture);
            }
        }
        
        public static string AlphaRecyclageDesc {
            get {
                return ResourceManager.GetString("AlphaRecyclageDesc", resourceCulture);
            }
        }
        
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        public static string AnalyticsDesc {
            get {
                return ResourceManager.GetString("AnalyticsDesc", resourceCulture);
            }
        }
        
        public static string ANSpricingLinkdesc {
            get {
                return ResourceManager.GetString("ANSpricingLinkdesc", resourceCulture);
            }
        }
        
        public static string BMZ {
            get {
                return ResourceManager.GetString("BMZ", resourceCulture);
            }
        }
        
        public static string BMZDesc {
            get {
                return ResourceManager.GetString("BMZDesc", resourceCulture);
            }
        }
        
        public static string BTS {
            get {
                return ResourceManager.GetString("BTS", resourceCulture);
            }
        }
        
        public static string BTSDesc {
            get {
                return ResourceManager.GetString("BTSDesc", resourceCulture);
            }
        }
        
        public static string DataVisioLinkdesc {
            get {
                return ResourceManager.GetString("DataVisioLinkdesc", resourceCulture);
            }
        }
        
        public static string DevAnalyticsSystemTitle {
            get {
                return ResourceManager.GetString("DevAnalyticsSystemTitle", resourceCulture);
            }
        }
        
        public static string DevLink {
            get {
                return ResourceManager.GetString("DevLink", resourceCulture);
            }
        }
        
        public static string ExchangeAnalytics {
            get {
                return ResourceManager.GetString("ExchangeAnalytics", resourceCulture);
            }
        }
        
        public static string ExchangeAnalyticsDesc {
            get {
                return ResourceManager.GetString("ExchangeAnalyticsDesc", resourceCulture);
            }
        }
        
        public static string Forecasting {
            get {
                return ResourceManager.GetString("Forecasting", resourceCulture);
            }
        }
        
        public static string ForecastingDesc {
            get {
                return ResourceManager.GetString("ForecastingDesc", resourceCulture);
            }
        }
        
        public static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string LightsamericaDesc {
            get {
                return ResourceManager.GetString("LightsamericaDesc", resourceCulture);
            }
        }
        
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        public static string NetDev {
            get {
                return ResourceManager.GetString("NetDev", resourceCulture);
            }
        }
        
        public static string NetLinkdesc {
            get {
                return ResourceManager.GetString("NetLinkdesc", resourceCulture);
            }
        }
        
        public static string OnlyMath {
            get {
                return ResourceManager.GetString("OnlyMath", resourceCulture);
            }
        }
        
        public static string OurProjects {
            get {
                return ResourceManager.GetString("OurProjects", resourceCulture);
            }
        }
        
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        public static string OurTeamDesc1 {
            get {
                return ResourceManager.GetString("OurTeamDesc1", resourceCulture);
            }
        }
        
        public static string OurTeamDesc2 {
            get {
                return ResourceManager.GetString("OurTeamDesc2", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string ProjectsLink {
            get {
                return ResourceManager.GetString("ProjectsLink", resourceCulture);
            }
        }
        
        public static string Props {
            get {
                return ResourceManager.GetString("Props", resourceCulture);
            }
        }
        
        public static string PropsDesc {
            get {
                return ResourceManager.GetString("PropsDesc", resourceCulture);
            }
        }
        
        public static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        public static string RetailDesc {
            get {
                return ResourceManager.GetString("RetailDesc", resourceCulture);
            }
        }
        
        public static string Robototech {
            get {
                return ResourceManager.GetString("Robototech", resourceCulture);
            }
        }
        
        public static string RobototechDesc {
            get {
                return ResourceManager.GetString("RobototechDesc", resourceCulture);
            }
        }
        
        public static string SellberyDesc {
            get {
                return ResourceManager.GetString("SellberyDesc", resourceCulture);
            }
        }
        
        public static string SoftwareForOurClients {
            get {
                return ResourceManager.GetString("SoftwareForOurClients", resourceCulture);
            }
        }
        
        public static string TeamLink {
            get {
                return ResourceManager.GetString("TeamLink", resourceCulture);
            }
        }
        
        public static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        public static string UsingDesc {
            get {
                return ResourceManager.GetString("UsingDesc", resourceCulture);
            }
        }
        
        public static string UsingLink {
            get {
                return ResourceManager.GetString("UsingLink", resourceCulture);
            }
        }
        
        public static string WeAlwaysOpen {
            get {
                return ResourceManager.GetString("WeAlwaysOpen", resourceCulture);
            }
        }
        
        public static string WhereCanUse {
            get {
                return ResourceManager.GetString("WhereCanUse", resourceCulture);
            }
        }
        
        public static string OurCurrentProjects {
            get {
                return ResourceManager.GetString("OurCurrentProjects", resourceCulture);
            }
        }
    }
}
